### ISSUE TITLE
单词数设为“1”, 依旧请求翻译

### ISSUE THREAD

**Issue by kaiyo655** [xingty/bob-plugin-youdao-dict-enhance#3]
<img width="1071" alt="截屏2023-05-18 18 32 43" src="https://github.com/xingty/bob-plugin-youdao-dict-enhance/assets/3762388/412de535-1ca9-4b07-bedc-c097035e35b4">
<img width="413" alt="截屏2023-05-18 18 31 17" src="https://github.com/xingty/bob-plugin-youdao-dict-enhance/assets/3762388/71ec089a-c71c-4314-a14f-4b7f1dfa7117">

如果是请求中文语段, 即使里面的英语单词>1, 也会被翻译

**Comment by xingty** [comment]
代码中确实只会对英文处理，处理其他语言的话，可能要考虑较多的细节。我看一下在下个版本如何修复这个问题。

**Comment by xingty** [comment]
这个问题已经在0.2.2中被修复，尝试更新一下。

**Comment by kaiyo655** [comment]
> 这个问题已经在0.2.2中被修复，尝试更新一下。

已经更新 超赞
