### ISSUE TITLE
无法处理换行的单词

### ISSUE THREAD

**Issue by zzsqwq** [xingty/bob-plugin-youdao-dict-enhance#4]
<img width="571" alt="CleanShot 2023-05-26 at 16 34 54@2x" src="https://github.com/xingty/bob-plugin-youdao-dict-enhance/assets/57089406/0a4c3048-29af-491f-9456-7e17b7d53fa8">

感谢您的插件，非常好用。

但使用中遇到了一个小问题，例如图上所示在某些文档中，如果单词出现了换行中断，选择出来是 `interpo- lation`，没法正确的识别是 `interpolation`，希望可以修复一下。

补充：我这里限制的单词数是 1，这种情况下应该是当两个单词对待了，所以无法显示出来。实测改成 2 后可以正确的翻译，但是这种情况可否当作一个单词来看待。

<img width="888" alt="CleanShot 2023-05-26 at 16 42 44@2x" src="https://github.com/xingty/bob-plugin-youdao-dict-enhance/assets/57089406/76fc8a1c-9888-4697-9358-03636b9539e5">

**Comment by xingty** [comment]
谢谢反馈。我抽个时间修复一下这问题。

**Comment by xingty** [comment]
在0.2.3修复了这个问题，尝试更新一下。

目前修复的只能处理"inter- polate"或"inter -polate"这些情况，即无法处理"inter-polate"。代码本身是没问题的，问题出在bob在处理"inter-polate"时，会自动把"-"替换为空格" "，比如下图: 

<img width="646" alt="Pasted Graphic" src="https://github.com/xingty/bob-plugin-youdao-dict-enhance/assets/3600657/f836e393-8dfb-43ef-9065-a9f00f782466">

"inter-polate"这种情况暂时是无解的，只能等bob处理。不过这通常来说也不是一个大问题，绝大部分情况下使用"-"连接的单词都存在换行情况，会带有一个空格。

因为我平时很少接触到带"-"的单词，如果还有问题欢迎继续反馈。

**Comment by zzsqwq** [comment]
嗯嗯，`inter-polate` 这种情况应该不是很多，0.2.3 目前使用起来没啥问题，感谢！
