### ISSUE TITLE
使用官网API翻译词组时, 显示有播放图标但无法播放.

### ISSUE THREAD

**Issue by wongchenv** [xingty/bob-plugin-youdao-dict-enhance#7]
<img width="397" alt="image" src="https://github.com/xingty/bob-plugin-youdao-dict-enhance/assets/14831158/499a21e0-2704-435f-9db3-5322dcb5d7ee">

**Comment by wongchenv** [comment]
另外希望可以对, 词组进行排版, 提高可读性

**Comment by wongchenv** [comment]
看起来真不错~

**Comment by wongchenv** [comment]
<img width="277" alt="image" src="https://github.com/xingty/bob-plugin-youdao-dict-enhance/assets/14831158/02cd3667-5afa-44b2-960f-cca60b6c5bdc">
另外有没有可能, 在排版上把"标签"并排于单词. 来释放纵向空间?

**Comment by wongchenv** [comment]
<img width="960" alt="image" src="https://github.com/xingty/bob-plugin-youdao-dict-enhance/assets/14831158/f126b2ef-79d6-4c2e-9695-06d8e7eec547">

在信息量方面, 有没有接入词根词缀的可能? 当然我这是开了有道会员, 如果不行有没有相关的API可以接入融合到有道插件.

**Comment by xingty** [comment]
> <img alt="image" width="277" src="https://user-images.githubusercontent.com/14831158/244126204-02cd3667-5afa-44b2-960f-cca60b6c5bdc.png">
> 另外有没有可能, 在排版上把"标签"并排于单词. 来释放纵向空间? 词组和例句排版后非常占用纵向空间. 也可以考虑, 自定义设置默认显示的词组与例句数量, 避免个别单词的词组与例句过长造成的用户体验问题.(如下图)
> 
> <img alt="image" width="1110" src="https://user-images.githubusercontent.com/14831158/244129108-464e9c11-4769-4585-9212-68e462d40ec1.png">

刚发布了0.2.6，修复了官方API无法朗读的问题。同时加上了可选词组数量功能。你提到的其他功能，尤其是跟排版相关的无法实现，因为bob并没有开放自己定制ui的功能。至于词根，在网页API下是可以实现的，不过目前信息已经很多，再加这功能感觉作用不是很大，后续看bob是否会开放一些定制界面功能再做打算。

**Comment by wongchenv** [comment]
一天一版本啊👍🏼 可以.
那建议把"标签"的部分也给个可选的隐藏权限. 我觉得没啥用, 隐藏了还能给词组多释放两条空间.

**Comment by xingty** [comment]
> 一天一版本啊👍🏼 可以. 那建议把"标签"的部分也给个可选的隐藏权限. 我觉得没啥用, 隐藏了还能给词组多释放两条空间.

标签这个我觉得作用也不大，后续版本会增加个选项隐藏起来，没啥问题这个issue我先关了哈。
